### PR TITLE
refactor: remove -d for ros2 caret command 

### PR DESCRIPTION
**Pull request by bopeng-saitama**
## Description

remove -d for ros2 caret command 

## Related links
Jira: https://tier4.atlassian.net/browse/RT2-975

## Pre-review checklist for the PR author

- [x] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [x] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR has been properly tested.
- [x] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.
- [x] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

### CODE REVIEW

**Review by rokamu623 — DISMISSED** [review]
LGTM

and it worked fine.

**Review by xygyo77 — DISMISSED** [review]
The following four commands were checked before and after the application of PR.
  - ros2 caret check_ctf
  - ros2 caret node_summary
  - ros2 caret topic_summary
  - ros2 caret trace_point_summary
  
[pr129-result.tar.gz](https://github.com/tier4/ros2caret/files/13163901/pr129-result.tar.gz)

**Review by takeshi-iwanari — CHANGES_REQUESTED** [review]
According to the original discussion, any unnecessary `-?` should be removed.
So, I think `-w`  in `check_caret_rclcpp` ~and `-f` in `create_architecture_file`~ should be also removed.

@nabetetsu 
Could you confirm if we remove them or not?

**Comment by takeshi-iwanari** [comment]
> But -f option in create_architecture_file should not be removed because it is used for overwriting the output file as optional action.

Oops, it's my bad. I fixed my original comment.

**Comment by bopeng-saitama** [comment]
> According to the original discussion, any unnecessary `-?` should be removed. So, I think `-w` in `check_caret_rclcpp` ~and `-f` in `create_architecture_file`~ should be also removed.
> 
> @nabetetsu Could you confirm if we remove them or not?

fixed in https://github.com/tier4/ros2caret/pull/129/commits/bf20e5e38d263b52ab91e37ce5dbe736d68f9506
截图 2023-10-26 11-07-09

**Review by takeshi-iwanari — APPROVED** [review]
Thank you for taking care of it!

**Review by rokamu623 — APPROVED** [review]
LGTM!

and it works fine:
image

**Pull request merged**
